

services:
  - type: web
    name: dollarnow-app
    env: php
    phpVersion: '8.2'
    buildCommand: |
      composer install --no-dev --optimize-autoloader
      php artisan key:generate --force
      php artisan storage:link
      php artisan migrate --force
    startCommand: php artisan serve --host 0.0.0.0 --port $PORT
    envVars:
      - key: APP_URL
        value: ${RENDER_EXTERNAL_URL}
      - key: APP_KEY
        generateValue: true
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: DATABASE_URL
        fromDatabase:
          name: dollarnow-db
          property: connectionString

databases:
  - name: dollarnow-db
    databaseName: dollarnow_db
    user: dollarnow_user
    plan: free